# Generated by Django 4.2.15 on 2024-09-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='descriptions',
            new_name='description',
        ),
    ]
