# Generated by Django 4.2.15 on 2024-11-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AddField(
            model_name='grocery',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
