# Generated by Django 4.2.15 on 2024-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_descriptions_grocery_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=249, verbose_name='Название элемента')),
                ('image', models.ImageField(default=None, null=True, upload_to='groceries/images/', verbose_name='Изображение элемента')),
                ('description', models.TextField(verbose_name='Описание элемента')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['name'],
            },
        ),
    ]
