# Generated by Django 4.2.15 on 2024-10-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='elements/images/', verbose_name='Изображение элемента'),
        ),
    ]
