# Generated by Django 4.2.15 on 2024-12-14 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_groceryimage_price_alter_grocery_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену в рублях. Пример: 1234.56', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на продукт (₽)'),
        ),
    ]
