# Generated by Django 4.2.15 on 2024-10-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_element_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=249, verbose_name='Название продукта')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Cертификат продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['name'], 'verbose_name': 'Группа продуктов', 'verbose_name_plural': 'Группы продуктов'},
        ),
        migrations.CreateModel(
            name='GroceryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='grocery_images/', verbose_name='Изображение продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.grocerydetail')),
            ],
            options={
                'verbose_name': 'Изображение к продукту',
                'verbose_name_plural': 'Изображение к продуктам',
                'ordering': ['product'],
            },
        ),
        migrations.AddField(
            model_name='grocerydetail',
            name='grocery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_detail', to='pages.grocery'),
        ),
    ]
