# Generated by Django 4.2.15 on 2024-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_groceryimage_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['id'], 'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AddField(
            model_name='element',
            name='char_limit',
            field=models.PositiveIntegerField(default=100, verbose_name='Количество символов до сокращения'),
        ),
    ]
