# Generated by Django 4.2.15 on 2024-12-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_element_options_element_char_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='action_link',
            field=models.CharField(max_length=50, null=True, verbose_name='Ссылка в конце карточки'),
        ),
        migrations.AddField(
            model_name='element',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать на странице'),
        ),
    ]
