# Generated by Django 4.2.15 on 2024-10-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_grocerydetail_alter_grocery_options_groceryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.grocerydetail', verbose_name='Категория продукта'),
        ),
    ]
