# Generated by Django 4.2.15 on 2024-10-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_groceryimage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['name'], 'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='groceryimage',
            options={'ordering': ['product'], 'verbose_name': 'Изображение к продукту', 'verbose_name_plural': 'Изображения к продукту'},
        ),
        migrations.AlterField(
            model_name='grocerydetail',
            name='grocery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_detail', to='pages.grocery', verbose_name='Категория продукта'),
        ),
    ]
