# Generated by Django 4.2.15 on 2024-12-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_element_action_link_element_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритетность'),
        ),
        migrations.AlterField(
            model_name='element',
            name='action_link',
            field=models.CharField(max_length=256, null=True, verbose_name='Ссылка в конце карточки'),
        ),
    ]
