# Generated by Django 4.2.15 on 2024-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_grocery_options_alter_groceryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryimage',
            name='description',
            field=models.TextField(default='No description', verbose_name='Описание изображения'),
        ),
    ]
