# Generated by Django 4.2.15 on 2024-10-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_groceryimage_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grocery',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='grocerydetail',
            old_name='grocery',
            new_name='category',
        ),
    ]
