# Generated by Django 4.2.15 on 2024-10-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_grocerydetail_grocery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_detail', to='pages.category', verbose_name='Категория продукта'),
        ),
    ]
