# Generated by Django 4.2.15 on 2024-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_grocery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_webp',
            field=models.ImageField(default=None, null=True, upload_to='groceries/images/webp/', verbose_name='Изображение продукта'),
        ),
        migrations.AddField(
            model_name='element',
            name='image_webp',
            field=models.ImageField(default=None, null=True, upload_to='elements/images/webp/', verbose_name='Изображение элемента'),
        ),
        migrations.AddField(
            model_name='groceryimage',
            name='image_webp',
            field=models.ImageField(default=None, null=True, upload_to='grocery_images/webp/', verbose_name='Изображение продукта'),
        ),
    ]
