# Generated by Django 4.2.15 on 2024-11-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_category_image_webp_element_image_webp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['name'], 'verbose_name': 'Страница продукта', 'verbose_name_plural': 'Страницы продуктов'},
        ),
        migrations.AddField(
            model_name='groceryimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать на странице'),
        ),
    ]
