# Generated by Django 4.2.15 on 2024-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_measurementunit_alter_groceryimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='category',
        ),
        migrations.AddField(
            model_name='grocery',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='groceries/images/', verbose_name='Изображение категории продукта'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='image_webp',
            field=models.ImageField(default=None, null=True, upload_to='groceries/images/webp/', verbose_name='Изображение категории продукта'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='main_description',
            field=models.TextField(default='0', null=True, verbose_name='Описание на главной странице'),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='description',
            field=models.TextField(verbose_name='Описание на странице продуктов'),
        ),
    ]
