# Generated by Django 4.2.15 on 2024-11-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_grocery_category_grocery_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
