# Generated by Django 4.2.15 on 2024-11-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['name'], 'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
    ]
