# Generated by Django 4.2.15 on 2024-11-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_grocery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='main_description',
            field=models.TextField(verbose_name='Описание на главной странице'),
        ),
    ]
